language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install: [ "npm install"]
addons:
  code_climate:
    repo_token: 2be9a1893c637f16694cb4d49a45c2364e329b88d28c344fdf3d2131eb03c55f
  coveralls:
    coveralls: WrgLsEQwpYftM5473BOk09AzlXNCqafNh
after_script:
  - ./node_modules/.bin/gulp coveralls
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info