language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install: [ "npm install"]
after_script:  
  - ./node_modules/.bin/gulp coveralls
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info